id:
name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
    - description: Auto-squash-merge PRs to main labeled with auto-merge
      triggerOnOwnActions: true
      if:
      - payloadType: Pull_Request
      - labelAdded:
          label: ':octocat: auto-merge'
      - targetsBranch:
          branch: main
      then:
      - enableAutoMerge:
          mergeMethod: Squash
    - description: Auto-merge PRs to live with title "Merge main into live"
      triggerOnOwnActions: true
      if:
      - payloadType: Pull_Request
      - isAction:
          action: Opened
      - titleContains:
          pattern: Merge main into live
          isRegex: False
      - targetsBranch:
          branch: live
      then:
      - enableAutoMerge:
          mergeMethod: Merge
    - description: Auto-merge PRs to live labeled with auto-merge
      triggerOnOwnActions: true
      if:
      - payloadType: Pull_Request
      - labelAdded:
          label: ':octocat: auto-merge'
      - targetsBranch:
          branch: live
      then:
      - enableAutoMerge:
          mergeMethod: Merge
    - description: Don't auto-merge PRs with auto-merge label removed
      if:
      - payloadType: Pull_Request
      - labelRemoved:
          label: ':octocat: auto-merge'
      then:
      - disableAutoMerge
