id:
name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
    - description: Label community PRs
      if:
      - payloadType: Pull_Request
      - isAction:
          action: Opened
      - and:
        - not:
            activitySenderHasPermission:
              permission: Admin
        - not:
            activitySenderHasPermission:
              permission: Write
        - not:
            isActivitySender:
              user: github-actions[bot]
        - not:
            isActivitySender:
              user: github-actions
        - not:
            isActivitySender:
              user: azure-sdk
        - not:
            isActivitySender:
              user: dependabot
      then:
      - addLabel:
          label: community-contribution

    - description: Label publish PRs from the dotnet-policy-service bot
      triggerOnOwnActions: true
      if:
      - payloadType: Pull_Request
      - isAction:
          action: Opened
      - isActivitySender:
          user: dotnet-policy-service[bot]
      - titleContains:
          pattern: Merge main into live
          isRegex: False
      then:
      - addLabel:
          label: ':octocat: auto-merge'

    - description: Label PRs from the Azure SDK bot
      if:
      - payloadType: Pull_Request
      - isActivitySender:
          user: azure-sdk
      then:
      - approvePullRequest:
          comment: "Approved; this PR will merge when all status checks pass."
      - addLabel:
          label: ':octocat: auto-merge'

    - description: Label PRs with okr-health
      if:
      - payloadType: Pull_Request
      - or:
        - titleContains:
            pattern: build warning
            isRegex: False
        - bodyContains:
            pattern: build warning
            isRegex: False
      then:
      - addLabel:
          label: okr-health

    - description: Label PRs with okr-freshness
      if:
      - payloadType: Pull_Request
      - or:
        - titleContains:
            pattern: freshness
            isRegex: False
        - bodyContains:
            pattern: freshness
            isRegex: False
      then:
      - addLabel:
          label: okr-freshness
