id:
name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: Flag PRs that change .github folder files.
        triggerOnOwnActions: true
        if:
          - payloadType: Pull_Request
          - isAction:
              action: Opened
          - filesMatchPattern:
              pattern: .github/*
              matchAny: true
              excludedFiles:
                - .github/CODEOWNERS
          - not:
              or:
                - activitySenderHasPermission:
                    permission: admin
                - activitySenderHasPermission:
                    permission: write
                - isActivitySender:
                    user: dependabot
                - isActivitySender:
                    user: dependabot[bot]
                - isActivitySender:
                    user: dotnet-policy-service[bot]
                - isActivitySender:
                    user: github-actions[bot]
        then:
          - addReply:
              reply: >-
                  @${issueAuthor} - This PR edits a file in the .github folder, which is not allowed. CC @dotnet/docs.
          - closePullRequest
