id: 
name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
owner: 
resource: repository
disabled: false
where: 
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
    - description: Label doc-bug issues with okr-health (scheduled search)
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: doc-bug
      - isNotLabeledWith:
          label: okr-health
      actions:
      - addLabel:
          label: okr-health
    eventResponderTasks:
    - if:
      - payloadType: Pull_Request
      then:
      - inPrLabel:
          label: in-pr
      description: Add in-pr label to issues
    - if:
      - payloadType: Pull_Request
      - isAction:
          action: Opened
      - and:
        - not:
            activitySenderHasPermission:
              permission: Admin
        - not:
            activitySenderHasPermission:
              permission: Write
        - not:
            isActivitySender:
              user: github-actions[bot]
              issueAuthor: False
        - not:
            isActivitySender:
              user: github-actions
              issueAuthor: False
        - not:
            isActivitySender:
              user: azure-sdk
              issueAuthor: False
        - not:
            isActivitySender:
              user: dependabot
              issueAuthor: False
      then:
      - addLabel:
          label: community-contribution
      description: Label community PRs
    - if:
      - payloadType: Pull_Request
      - isActivitySender:
          user: azure-sdk
          issueAuthor: False
      then:
      - approvePullRequest:
          comment: "Approved, we'll :shipit: when all status checks pass."
      - addLabel:
          label: azure-sdk-shipit
      description: Label PRs from the Azure SDK bot
    - if:
      - payloadType: Pull_Request
      - hasLabel:
          label: azure-sdk-shipit
      then:
      - enableAutoMerge:
          mergeMethod: Squash
      description: Auto-merge Azure SDK PRs with green builds
    - if:
      - payloadType: Pull_Request
      - labelRemoved:
          label: azure-sdk-shipit
      then:
      - disableAutoMerge
      description: Auto-merge Azure SDK PRs with green builds
    - if:
      - payloadType: Issues
      - titleContains:
          pattern: (T|t)ypo
          isRegex: True
      then:
      - addLabel:
          label: doc-bug
      - addLabel:
          label: help wanted
      - addLabel:
          label: good first issue
      description: Label typo issues as help wanted
    - if:
      - payloadType: Pull_Request
      then:
      - labelSync:
          pattern: okr-
      - labelSync:
          pattern: ':checkered_flag: Release'
      description: Synchronize OKR and release labels between issues/PRs
    - if:
      - payloadType: Issues
      - or:
        - hasLabel:
            label: doc-bug
        - titleContains:
            pattern: freshness
            isRegex: False
        - titleContains:
            pattern: out( |-)of( |-)date
            isRegex: True
      then:
      - addLabel:
          label: okr-health
      description: Label issues with okr-health (event-based)
    - if:
      - payloadType: Pull_Request
      - or:
        - titleContains:
            pattern: build warning
            isRegex: False
        - bodyContains:
            pattern: build warning
            isRegex: False
        - titleContains:
            pattern: freshness
            isRegex: False
      then:
      - addLabel:
          label: okr-health
      description: Label PRs with okr-health
onFailure: 
onSuccess:
