ITypedList.exe:  BusinessObjectBase.vb Employee.vb EmployeeListSource.vb Form1.vb
   vbc /t:exe /out:ITypedList.exe BusinessObjectBase.vb Employee.vb EmployeeListSource.vb Form1.vb

clean:
   del *.dll *.bin *.exe