all : net_async.exe nmake_async.exe sort_async.exe

net_async.exe : net_async.cpp
	cl /clr:pure /LD net_async.cpp

nmake_async.exe : nmake_async.cpp
	cl /clr:pure /LD nmake_async.cpp

sort_async.exe :  sort_async.cpp
	cl /clr:pure /LD  sort_async.cpp 
