        Debug.WriteLine(10 Mod 5)
        ' Output: 0
        Debug.WriteLine(10 Mod 3)
        ' Output: 1
        Debug.WriteLine(-10 Mod 3)
        ' Output: -1
        Debug.WriteLine(12 Mod 4.3)
        ' Output: 3.4
        Debug.WriteLine(12.6 Mod 5)
        ' Output: 2.6
        Debug.WriteLine(47.9 Mod 9.35)
        ' Output: 1.15