all : net_async.exe nmake_async.exe sort_async.exe

net_async.exe : net_async.vb
	vbc net_async.vb

nmake_async.exe : nmake_async.vb
	vbc nmake_async.vb

sort_async.exe :  sort_async.vb
	vbc  sort_async.vb
