all: XmlSerializerFormat_Example.exe 
XmlSerializerFormat_Example.exe: XmlSerializerFormat_Example.vb
 vbc /t:exe *.vb /r:System.ServiceModel.dll,System.Runtime.Serialization.dll /libpath:C:\Whidbey\Assemblies