all: source.exe
 
source.exe: source.cs
 csc /t:exe source.cs /r:System.Web.ApplicationServices.dll,System.ServiceModel.dll,System.dll,System.Configuration.dll,System.Runtime.Serialization.dll,System.IdentityModel.dll