HelpLabelTest.exe:  HelpLabel.vb HostApp.vb
   vbc /t:exe /r:System.Design.dll,System.dll,System.Drawing.dll,System.Windows.Forms.dll /out:HelpLabelTest.exe HelpLabel.vb HostApp.vb

clean:
   del *.exe *.bin