        Dim kindergarten As Integer = students(0)
        Dim firstGrade As Integer = students(1)
        Dim sixthGrade As Integer = students(6)
        MsgBox("Students in kindergarten = " & CStr(kindergarten))
        MsgBox("Students in first grade = " & CStr(firstGrade))
        MsgBox("Students in sixth grade = " & CStr(sixthGrade))