version: 2
updates:
  # Updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      github-actions:
        patterns: ["*"]
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3
    # NuGet updates for AI, Architecture, Azure, Core, Csharp, and DevOps snippets
  - package-ecosystem: "nuget"
    directories:
      - "docs/ai/**/snippets/**/*"
      - "docs/architecture/**/snippets/**/*"
      - "docs/azure/**/snippets/**/*"
      - "docs/core/**/snippets/**/*"
      - "docs/csharp/**/snippets/**/*"
      - "docs/devops/**/snippets/**/*"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    cooldown:
      default-days: 7
    groups:
      nuget:
        patterns: ["*"]
        group-by: dependency-name
    # NuGet updates for F#, Fundamentals, and Framework snippets.
  - package-ecosystem: "nuget"
    directories:
      - "docs/fsharp/**/snippets/**/*"
      - "docs/framework/**/snippets/**/*"
      - "docs/fundamentals/**/snippets/**/*"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    cooldown:
      default-days: 7
    groups:
      nuget:
        patterns: ["*"]
        group-by: dependency-name
    # NuGet updates for IoT, Machine Learning, Standard, and Visual Basic snippets.
  - package-ecosystem: "nuget"
    directories:
      - "docs/iot/**/snippets/**/*"
      - "docs/machine-learning/**/snippets/**/*"
      - "docs/standard/**/snippets/**/*"
      - "docs/visual-basic/**/snippets/**/*"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    cooldown:
      default-days: 7
    groups:
      nuget:
        patterns: ["*"]
        group-by: dependency-name
    # NuGet updates for non-V3 Orleans snippets.
  - package-ecosystem: "nuget"
    directories:
      - "docs/orleans/**/snippets/**/*"
    exclude-paths:
      - "docs/orleans/**/snippets-v3/**/*"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    cooldown:
      default-days: 7
    groups:
      nuget:
        patterns: ["*"]
        group-by: dependency-name
    # NuGet updates for Orleans V3 snippets.
  - package-ecosystem: "nuget"
    directories:
      - "docs/orleans/**/snippets-v3/**/*"
    exclude-paths:
      - "docs/orleans/**/snippets/**/*"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    cooldown:
      default-days: 7
    groups:
      nuget:
        patterns: ["*"]
        group-by: dependency-name
    # NuGet updates for samples/snippets
  - package-ecosystem: "nuget"
    directories:
      - "samples/snippets/**/*"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    cooldown:
      default-days: 7
    groups:
      nuget:
        patterns: ["*"]
        group-by: dependency-name
