version: 2
updates:
  # Updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      github-actions:
        patterns: ["*"]
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "nuget"
    directories:
      - "**/snippets/**/*"
      - "**/snippets-v3/**/*"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    cooldown:
      default-days: 7
    groups:
      nuget:
        patterns: ["*"]
        group-by: dependency-name
