Program.exe: service.cs 
 csc /t:exe service.cs /r:System.dll,System.ServiceModel.dll,System.IdentityModel.dll,System.Xml.dll,System.Configuration.dll,System.Runtime.Serialization.dll /lib:c:\whidbey\assemblies
