Program.exe: Program.cs 
 csc /t:exe Program.cs service.cs /r:System.dll,System.ServiceModel.dll,System.Data.dll,System.IdentityModel.dll,System.ServiceModel.dll,System.Xml.dll,System.Configuration.dll 
