FlashTrackBarText.exe:  FlashTrackBar.cs FlashTrackBarDarkenByEditor.cs FlashTrackBarValueEditor.cs HostApp.cs
   csc /t:exe /out:FlashTrackBar.exe FlashTrackBar.cs FlashTrackBarDarkenByEditor.cs FlashTrackBarValueEditor.cs HostApp.cs

clean:
   del *.exe *.bin