all: c_CustomFederationBinding.exe
 
c_CustomFederationBinding.exe: c_CustomFederationBinding.cs 
 csc /t:exe *.cs /r:System.ServiceModel.dll,System.Runtime.Serialization.dll,System.IdentityModel.dll /lib:c:\whidbey\assemblies
