revision: 7
schema-version: 5
owner-ms-alias: adegeo

config:
  DocMetadata:
    Headers:
      - ["---", "#### "]

    ParserRegex: "^\\* (.*): (.*)$"

    ContentUrlRegex:
      - "### Page URL\n\n(.*)"

issues:

  opened:

    # Add links to related issues if it's a doc issue
    - check:
        - type: metadata-exists
        - type: variable-exists
          name: "document_version_independent_id"
      pass:
        - link-related-issues

    - check:
        - type: metadata-exists
      pass:
        - svc_subsvc_labels: true

projects_v2_item:

  reordered:

    - labels-add: [":world_map: mapQUEST"]

  edited:

    - check:
        - type: query
          value: "EventPayload.changes.field_value.field_name == 'Priority' || EventPayload.changes.field_value.field_name == 'Size'"
      pass:
        - labels-add: [":world_map: mapQUEST"]

pull_request:

  reopened: opened

  opened:

    # Set default sprint for new PRs
    - milestone-set: "![sprint]"
  