revision: 6
schema-version: 5
owner-ms-alias: adegeo

config:
  DocMetadata:
    Headers:
      - ["---", "#### "]

    ParserRegex: "^\\* (.*): (.*)$"

    ContentUrlRegex:
      - "### Page URL\n\n(.*)"

issues:

  unlabeled: "labeled"
  
  labeled:

    # Temporary label to mark issues as updated for Quest. The label is instantly removed
    - check:
        - type: query
          value: "length(Issue.Labels[?Name == ':world_map: mapQUEST']) != `0`"
      pass:
        - labels-remove: [":world_map: mapQUEST"]

    # Handle issues with /svc /subsvc labels from label bot
    - check:
        - type: query
          value: "length(Issue.Labels[?contains(Name, '/svc') || contains(Name, '/subsvc')]) != `0`"

      # If the issue has a /svc or /subsvc label, it must be categorized otherwise it's considered untriaged
      pass:
        - check:
          - type: query
            value: "length(Issue.Labels[?Name == ':pushpin: seQUESTered' || Name == ':world_map: reQUEST' || Name == 'training-module' || Name == 'doc-enhancement' || Name == 'product-question' || Name == 'in-progress' || Name == 'test-issue' || Name == 'kudos' || Name == 'loc' || Name == 'doc-bug' || Name == 'product-feedback' || Name == 'code-of-conduct' || Name == 'support-request' || Name == 'duplicate' || Name == 'resolved-by-customer' || Name == 'docs-experience' || Name == 'doc-provided' || Name == 'doc-idea' || Name == 'needs-more-info']) != `0`"
          pass:
            - labels-remove: [":watch: Not Triaged"]
          fail:
            - labels-add: [":watch: Not Triaged"]

      # Not an doc issue specifically
      fail:

        # If the issue is open, then we'll allow some further processing on it. If it's closed, ignore it and let the user do what they want.
        - check:
          - type: query
            value: "Issue.State.StringValue == 'open'"

          pass:
            - check:
              - type: query
                value: "length(Issue.Labels[?Name == ':pushpin: seQUESTered' || Name == ':world_map: reQUEST' || Name == 'training-module' || Name == 'video-content'] || Name == 'test-issue') != `0`"
              pass:
                - labels-remove: [":watch: Not Triaged"]
              fail:
                - labels-add: [":watch: Not Triaged"]

    # Checks for binary/source incompatible checkboxes and adds a label
    - check:
        - type: query
          value: "contains(InstanceData.IssuePrBody, '- [x] **Binary incompatible**') == `true` || contains(InstanceData.IssuePrBody, '- [X] **Binary incompatible**') == `true`"
      pass:
        - labels-add: ["binary incompatible"]

    - check:
        - type: query
          value: "contains(InstanceData.IssuePrBody, '- [x] **Source incompatible**') == `true` || contains(InstanceData.IssuePrBody, '- [X] **Source incompatible**') == `true`"
      pass:
        - labels-add: ["source incompatible"]

  opened:
    # New issue opened, add Not Triaged  
    - labels-add: [":watch: Not Triaged"]

    # Dependabot opened issue, label it
    - check:
        - type: query
          value: "Issue.User.Login == 'dependabot'"
      pass:
        - labels-add: ["dependencies"]

    # Try to detect an empty issue
    - check:
        - type: comment-body
          value: "### Description[\\n\\r]+\\[Enter feedback here\\][\\n\\r]+###"
      pass:
        - labels-add: ["needs-more-info"]
        - labels-remove: [":watch: Not Triaged"]
        - close

    # Add links to related issues if it's a doc issue
    - check:
        - type: metadata-exists
        - type: variable-exists
          name: "document_version_independent_id"
      pass:
        - link-related-issues

  reopened:

    # Remove won't fix label
    - labels-remove: ["won't fix"]

  closed:

    # Issue closed, remove in-progress and not triaged labels
    - labels-remove: ["in-progress", ":watch: Not Triaged"]

    # Check if the issue was closed by the user who opened it
    - check:
        - type: query
          value: "Issue.User.Id == EventPayload.sender.id"
      pass:
        - labels-add: ["resolved-by-customer"]
        - labels-remove: [":watch: Not Triaged"]

projects_v2_item:

  reordered:

    - labels-add: [":world_map: mapQUEST"]

  edited:

    - check:
        - type: query
          value: "EventPayload.changes.field_value.field_name == 'Priority' || EventPayload.changes.field_value.field_name == 'Size'"
      pass:
        - labels-add: [":world_map: mapQUEST"]

pull_request:

  reopened: opened

  opened:

    # Set default sprint for new PRs
    - milestone-set: "![sprint]"
  
    - check:
        - type: query
          value: "PullRequest.Base.Ref != 'live'"
      pass:
        - files-changed:
            # csharplang
            - path: "(?i).*_csharplang.*"
              run:
                - labels-add: ["dotnet-csharp/svc", "lang-spec/subsvc"]

            # csharpstandard
            - path: "(?i).*_csharpstandard.*"
              run:
                - labels-add: ["dotnet-csharp/svc", "lang-spec/subsvc"]

            # vbspec
            - path: "(?i).*_vblang\/spec.*"
              run:
                - labels-add: ["dotnet-visualbasic/svc", "vb-spec/subsvc"]

            # architecture
            - path: "(?i).*docs\/architecture.*"
              run:
                - labels-add: ["dotnet-architecture/svc"]
            - path: "(?i).*docs\/architecture\/blazor-for-web-forms-developers.*"
              run:
                - labels-add: ["dotnet-architecture/svc", "blazor/subsvc"]
            - path: "(?i).*docs\/architecture\/cloud-native.*"
              run:
                - labels-add: ["dotnet-architecture/svc", "cloud-native/subsvc"]
            - path: "(?i).*docs\/architecture\/containerized-lifecycle.*"
              run:
                - labels-add: ["dotnet-architecture/svc", "containerized-lifecycle/subsvc"]
            - path: "(?i).*docs\/architecture\/grpc-for-wcf-developers.*"
              run:
                - labels-add: ["dotnet-architecture/svc", "grpc/subsvc"]
            - path: "(?i).*docs\/architecture\/microservices.*"
              run:
                - labels-add: ["dotnet-architecture/svc", "microservices/subsvc"]
            - path: "(?i).*docs\/architecture\/modernize-with-azure-containers.*"
              run:
              - labels-add: ["dotnet-architecture/svc", "modernize-with-azure-containers/subsvc"]
            - path: "(?i).*docs\/architecture\/modern-web-apps-azure.*"
              run:
                - labels-add: ["dotnet-architecture/svc", "modern-web-apps-azure/subsvc"]
            - path: "(?i).*docs\/architecture\/serverless.*"
              run:
                - labels-add: ["dotnet-architecture/svc", "serverless/subsvc"]

            # azure
            - path: "(?i).*docs\/azure.*"
              run:
                - labels-add: ["dotnet-azure/svc"]
            
            # core
            - path: "(?i).*docs\/core.*"
              run:
                - labels-add: ["dotnet-fundamentals/svc"]
            - path: "(?i).*docs\/core\/tools.*"
              run:
                - labels-add: ["dotnet-fundamentals/svc", "dotnet-cli/subsvc"]
            - path: "(?i).*docs\/core\/docker.*"
              run:
                - labels-add: ["dotnet-fundamentals/svc", "dotnet-docker/subsvc"]
            
            # core/install
            - path: "(?i).*docs\/core\/install.*"
              run:
                - labels-add: ["dotnet-fundamentals/svc", "install/subsvc"]

            # csharp
            - path: "(?i).*docs\/csharp.*"
              run:
                - labels-add: ["dotnet-csharp/svc"]
            - path: "(?i).*docs\/csharp\/fundamentals.*"
              run:
                - labels-add: ["dotnet-csharp/svc", "fundamentals/subsvc"]
            - path: "(?i).*docs\/csharp\/misc.*"
              run:
                - labels-add: ["dotnet-csharp/svc", "csharp-errors-warnings/subsvc"]
            - path: "(?i).*docs\/csharp\/whats-new.*"
              run:
                - labels-add: ["dotnet-csharp/svc", "whats-new/subsvc"]
            - path: "(?i).*docs\/csharp\/how-to.*"
              run:
                - labels-add: ["dotnet-csharp/svc", "fundamentals/subsvc"]
            - path: "(?i).*docs\/csharp\/linq.*"
              run:
                - labels-add: ["dotnet-csharp/svc", "csharp-linq/subsvc"]
            - path: "(?i).*docs\/csharp\/programming-guide\/indexers.*"
              run:
                - labels-add: ["dotnet-csharp/svc", "fundamentals/subsvc"]
            - path: "(?i).*docs\/csharp\/programming-guide\/generics.*"
              run:
                - labels-add: ["dotnet-csharp/svc", "fundamentals/subsvc"]
            - path: "(?i).*docs\/csharp\/programming-guide\/strings.*"
              run:
                - labels-add: ["dotnet-csharp/svc", "fundamentals/subsvc"]
            - path: "(?i).*docs\/csharp\/programming-guide\/types.*"
              run:
                - labels-add: ["dotnet-csharp/svc", "fundamentals/subsvc"]
            - path: "(?i).*docs\/csharp\/programming-guide\/statements-expressions-operators.*"
              run:
                - labels-add: ["dotnet-csharp/svc", "fundamentals/subsvc"]
            - path: "(?i).*docs\/csharp\/programming-guide\/interop.*"
              run:
                - labels-add: ["dotnet-csharp/svc", "advanced-concepts/subsvc"]
            - path: "(?i).*docs\/csharp\/language-reference\/unsafe-code.*"
              run:
                - labels-add: ["dotnet-csharp/svc", "advanced-concepts/subsvc"]
            - path: "(?i).*docs\/csharp\/programming-guide\/namespaces.*"
              run:
                - labels-add: ["dotnet-csharp/svc", "fundamentals/subsvc"]
            - path: "(?i).*docs\/csharp\/programming-guide\/arrays.*"
              run:
                - labels-add: ["dotnet-csharp/svc", "fundamentals/subsvc"]
            - path: "(?i).*docs\/csharp\/programming-guide\/concepts\/covariance-contravariance.*"
              run:
                - labels-add: ["dotnet-csharp/svc", "advanced-concepts/subsvc"]
            - path: "(?i).*docs\/csharp\/programming-guide\/concepts\/serialization.*"
              run:
                - labels-add: ["dotnet-csharp/svc", "fundamentals/subsvc"]
            - path: "(?i).*docs\/csharp\/programming-guide\/concepts\/expression-trees.*"
              run:
                - labels-add: ["dotnet-csharp/svc", "advanced-concepts/subsvc"]
            - path: "(?i).*docs\/csharp\/asynchronous-programming\/.*"
              run:
                - labels-add: ["dotnet-csharp/svc", "async-task-programming/subsvc"]
            - path: "(?i).*docs\/csharp\/programming-guide\/concepts\/linq.*"
              run:
                - labels-add: ["dotnet-csharp/svc", "csharp-linq/subsvc"]
            - path: "(?i).*docs\/csharp\/programming-guide\/concepts\/attributes.*"
              run:
                - labels-add: ["dotnet-csharp/svc", "fundamentals/subsvc"]
            - path: "(?i).*docs\/csharp\/programming-guide\/xmldoc.*"
              run:
                - labels-add: ["dotnet-csharp/svc", "fundamentals/subsvc"]
            - path: "(?i).*docs\/csharp\/programming-guide\/classes-and-structs.*"
              run:
                - labels-add: ["dotnet-csharp/svc", "fundamentals/subsvc"]
            - path: "(?i).*docs\/csharp\/programming-guide\/delegates.*"
              run:
                - labels-add: ["dotnet-csharp/svc", "fundamentals/subsvc"]
            - path: "(?i).*docs\/csharp\/programming-guide\/file-system.*"
              run:
                - labels-add: ["dotnet-csharp/svc", "fundamentals/subsvc"]
            - path: "(?i).*docs\/csharp\/programming-guide\/events.*"
              run:
                - labels-add: ["dotnet-csharp/svc", "fundamentals/subsvc"]
            - path: "(?i).*docs\/csharp\/programming-guide\/interfaces.*"
              run:
                - labels-add: ["dotnet-csharp/svc", "fundamentals/subsvc"]
            - path: "(?i).*docs\/csharp\/tutorials.*"
              run:
                - labels-add: ["dotnet-csharp/svc", "fundamentals/subsvc"]
            - path: "(?i).*docs\/csharp\/tutorials\/exploration.*"
              run:
                - labels-add: ["dotnet-csharp/svc", "get-started/subsvc"]
            - path: "(?i).*docs\/csharp\/language-reference.*"
              run:
                - labels-add: ["dotnet-csharp/svc", "lang-reference/subsvc"]
            - path: "(?i).*docs\/csharp\/language-reference\/compiler-messages.*"
              run:
                - labels-add: ["dotnet-csharp/svc", "csharp-diagnostics/subsvc"]
            - path: "(?i).*docs\/csharp\/roslyn-sdk.*"
              run:
                - labels-add: ["dotnet-csharp/svc", "roslyn-sdk/subsvc"]
            - path: "(?i).*docs\/csharp\/tour-of-csharp.*"
              run:
                - labels-add: ["dotnet-csharp/svc", "get-started/subsvc"]

            # framework
            - path: "(?i).*docs\/framework.*"
              run:
                - labels-add: ["dotnet-framework/svc"]
            - path: "(?i).*docs\/framework\/configure-apps\/file-schema\/network.*"
              run:
                - labels-add: [ "dotnet-framework/svc", "networking/subsvc" ]
            - path: "(?i).*docs\/framework\/configure-apps\/file-schema\/wcf.*"
              run:
                - labels-add: [ "dotnet-framework/svc", "wcf/subsvc" ]
            - path: "(?i).*docs\/framework\/data\/adonet.*"
              run:
                - labels-add: [ "dotnet-framework/svc", "data-access/subsvc" ]
            - path: "(?i).*docs\/framework\/data\/wcf.*"
              run:
                - labels-add: [ "dotnet-framework/svc", "wcf/subsvc" ]
            - path: "(?i).*docs\/framework\/docker.*"
              run:
                - labels-add: [ "dotnet-framework/svc", "dotnet-docker/subsvc" ]
            - path: "(?i).*docs\/framework\/install.*"
              run:
                - labels-add: [ "dotnet-framework/svc", "install/subsvc" ]
            - path: "(?i).*docs\/framework\/migration-guide.*"
              run:
                - labels-add: [ "dotnet-framework/svc", "app-compat/subsvc" ]
            - path: "(?i).*docs\/framework\/network-programming.*"
              run:
                - labels-add: [ "dotnet-framework/svc", "dotnet-networking/subsvc" ]
            - path: "(?i).*docs\/fundamentals\/networking.*"
              run:
                - labels-add: [ "dotnet-fundamentals/svc", "dotnet-networking/subsvc" ]
            - path: "(?i).*docs\/core\/extensions\/http.*"
              run:
                - labels-add: [ "dotnet-fundamentals/svc", "dotnet-networking/subsvc" ]
            - path: "(?i).*docs\/framework\/wcf.*"
              run:
                - labels-add: [ "dotnet-framework/svc", "dotnet-wcf/subsvc" ]
            - path: "(?i).*docs\/framework\/windows-workflow-foundation.*"
              run:
                - labels-add: [ "dotnet-framework/svc", "wf/subsvc" ]
            
            # fsharp
            - path: "(?i).*docs\/fsharp.*"
              run:
                - labels-add: ["dotnet-fsharp/svc"]
            
            # fundamentals
            - path: "(?i).*docs\/fundamentals.*"
              run:
                - labels-add: ["dotnet-fundamentals/svc"]
            
            # standard
            - path: "(?i).*docs\/standard.*"
              run:
                - labels-add: ["dotnet-fundamentals/svc"]
            
            # analyzers
            - path: "(?i).*docs\/standard\/analyzers.*"
              run:
                - labels-add: [ "dotnet-fundamentals/svc", "code-analyzers/subsvc" ]
            
            # machine learning
            - path: "(?i).*docs\/machine-learning.*"
              run:
                - labels-add: ["dotnet-ml/svc"]
            
            # spark
            - path: "(?i).*docs\/spark.*"
              run:
                - labels-add: ["dotnet-spark/svc"]
            
            # data
            - path: "(?i).*docs\/standard\/data.*"
              run:
                - labels-add: ["dotnet-data/svc"]
            
            # design guidelines
            - path: "(?i).*docs\/standard\/design-guidelines.*"
              run:
                - labels-add: [ "dotnet/svc", "standard-library/subsvc" ]
            
            # security
            - path: "(?i).*docs\/standard\/security.*"
              run:
                - labels-add: [ "dotnet/svc", "security-practices/subsvc" ]
            
            # visual-basic
            - path: "(?i).*docs\/visual-basic.*"
              run:
                - labels-add: ["dotnet-visualbasic/svc"]
            
            # visual-basic lang ref error messages
            - path: "(?i).*docs\/visual-basic\/language-reference\/error-messages.*"
              run:
                - labels-add: [ "dotnet-visualbasic/svc", "errors-warnings/subsvc" ]
            
            # visual-basic misc
            - path: "(?i).*docs\/visual-basic\/misc.*"
              run:
                - labels-add: ["dotnet-visualbasic/svc", "errors-warnings/subsvc"]

issue_comment:

  created:

    # someone creates a comment with #please-review in it, add changes-addressed label
    - check:
        - type: query
          value: "Issue.State.StringValue == 'open' && Issue.User.Id == Comment.User.Id"
        - type: comment-body
          value: ^#please-review$
      pass:
        - labels-add: ["changes-addressed"]
