#! /usr/bin/env bash

# This script is a helper for generating a new, templated doc entry.
# It must be invoked from its parent directory, `compiler-messages`, like this: 
# `./util/new-message <4-digit error number> "title of new error page"`
# It ensures some title, date, and SEO keywords are in place for the new file.

set +eux

function usage () {
    echo "usage: new-message <####> <title>"
    exit 1;
}

[[ -z $1 || $# -gt 2 ]] && usage

message_number="FS$1"
message_title=$2
year=$(date "+%Y")
month=$(date "+%m")
day=$(date "+%d")
md_file_name="fs$1.md"
fsx_file_name="fs$1.fsx"

echo "Writing ${md_file_name}"

cat >"${md_file_name}" <<EOF
---
title: "Compiler error $message_number"
ms.date: $month/$day/$year
f1_keywords:
  - "$message_number"
helpviewer_keywords:
  - "$message_number"
---

# $message_number: $message_title

[!code-fsharp[$message_number-comment](~/samples/snippets/fsharp/compiler-messages/$fsx_file_name#L2-L3)]
EOF

echo "Writing TOC entry"

cat >>toc.yml <<EOF
  - name: $message_number - $message_title
    href: ./$md_file_name
EOF

echo "Writing ${fsx_file_name}"

cat >"../../../../samples/snippets/fsharp/compiler-messages/${fsx_file_name}" <<EOF
(* comment *)
let someCode = "Some code"
printfn "%s" someCode
EOF
