'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Namespace Microsoft.ServiceModel.Samples


	'<snippet1>
	<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"), System.ServiceModel.ServiceContractAttribute(Namespace:="http://Microsoft.ServiceModel.Samples", ConfigurationName:="Microsoft.ServiceModel.Samples.ICalculator")> _
	Public Interface ICalculator

		<System.ServiceModel.OperationContractAttribute(Action:="http://Microsoft.ServiceModel.Samples/ICalculator/Add", ReplyAction:="http://Microsoft.ServiceModel.Samples/ICalculator/AddResponse")> _
		Function Add(ByVal n1 As Double, ByVal n2 As Double) As Double

		<System.ServiceModel.OperationContractAttribute(AsyncPattern:=True, Action:="http://Microsoft.ServiceModel.Samples/ICalculator/Add", ReplyAction:="http://Microsoft.ServiceModel.Samples/ICalculator/AddResponse")> _
		Function BeginAdd(ByVal n1 As Double, ByVal n2 As Double, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult

		Function EndAdd(ByVal result As System.IAsyncResult) As Double
	'<snippet1>

		<System.ServiceModel.OperationContractAttribute(Action:="http://Microsoft.ServiceModel.Samples/ICalculator/Subtract", ReplyAction:="http://Microsoft.ServiceModel.Samples/ICalculator/SubtractResponse")> _
		Function Subtract(ByVal n1 As Double, ByVal n2 As Double) As Double

		<System.ServiceModel.OperationContractAttribute(AsyncPattern:=True, Action:="http://Microsoft.ServiceModel.Samples/ICalculator/Subtract", ReplyAction:="http://Microsoft.ServiceModel.Samples/ICalculator/SubtractResponse")> _
		Function BeginSubtract(ByVal n1 As Double, ByVal n2 As Double, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult

		Function EndSubtract(ByVal result As System.IAsyncResult) As Double

		<System.ServiceModel.OperationContractAttribute(Action:="http://Microsoft.ServiceModel.Samples/ICalculator/Multiply", ReplyAction:="http://Microsoft.ServiceModel.Samples/ICalculator/MultiplyResponse")> _
		Function Multiply(ByVal n1 As Double, ByVal n2 As Double) As Double

		<System.ServiceModel.OperationContractAttribute(AsyncPattern:=True, Action:="http://Microsoft.ServiceModel.Samples/ICalculator/Multiply", ReplyAction:="http://Microsoft.ServiceModel.Samples/ICalculator/MultiplyResponse")> _
		Function BeginMultiply(ByVal n1 As Double, ByVal n2 As Double, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult

		Function EndMultiply(ByVal result As System.IAsyncResult) As Double

		<System.ServiceModel.OperationContractAttribute(Action:="http://Microsoft.ServiceModel.Samples/ICalculator/Divide", ReplyAction:="http://Microsoft.ServiceModel.Samples/ICalculator/DivideResponse")> _
		Function Divide(ByVal n1 As Double, ByVal n2 As Double) As Double

		<System.ServiceModel.OperationContractAttribute(AsyncPattern:=True, Action:="http://Microsoft.ServiceModel.Samples/ICalculator/Divide", ReplyAction:="http://Microsoft.ServiceModel.Samples/ICalculator/DivideResponse")> _
		Function BeginDivide(ByVal n1 As Double, ByVal n2 As Double, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult

		Function EndDivide(ByVal result As System.IAsyncResult) As Double
	End Interface

	<System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")> _
	Public Interface ICalculatorChannel
	Inherits Microsoft.ServiceModel.Samples.ICalculator, System.ServiceModel.IClientChannel
	End Interface

	<System.Diagnostics.DebuggerStepThroughAttribute(), System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")> _
	Partial Public Class CalculatorClient
		Inherits System.ServiceModel.ClientBase(Of Microsoft.ServiceModel.Samples.ICalculator)
		Implements Microsoft.ServiceModel.Samples.ICalculator

		Public Sub New()
		End Sub

		Public Sub New(ByVal endpointConfigurationName As String)
			MyBase.New(endpointConfigurationName)
		End Sub

		Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
			MyBase.New(endpointConfigurationName, remoteAddress)
		End Sub

		Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
			MyBase.New(endpointConfigurationName, remoteAddress)
		End Sub

		Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
			MyBase.New(binding, remoteAddress)
		End Sub

		Public Function Add(ByVal n1 As Double, ByVal n2 As Double) As Double Implements Microsoft.ServiceModel.Samples.ICalculator.Add
			Return MyBase.Channel.Add(n1, n2)
		End Function

		Public Function BeginAdd(ByVal n1 As Double, ByVal n2 As Double, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements Microsoft.ServiceModel.Samples.ICalculator.BeginAdd
			Return MyBase.Channel.BeginAdd(n1, n2, callback, asyncState)
		End Function

		Public Function EndAdd(ByVal result As System.IAsyncResult) As Double Implements Microsoft.ServiceModel.Samples.ICalculator.EndAdd
			Return MyBase.Channel.EndAdd(result)
		End Function

		Public Function Subtract(ByVal n1 As Double, ByVal n2 As Double) As Double Implements Microsoft.ServiceModel.Samples.ICalculator.Subtract
			Return MyBase.Channel.Subtract(n1, n2)
		End Function

		Public Function BeginSubtract(ByVal n1 As Double, ByVal n2 As Double, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements Microsoft.ServiceModel.Samples.ICalculator.BeginSubtract
			Return MyBase.Channel.BeginSubtract(n1, n2, callback, asyncState)
		End Function

		Public Function EndSubtract(ByVal result As System.IAsyncResult) As Double Implements Microsoft.ServiceModel.Samples.ICalculator.EndSubtract
			Return MyBase.Channel.EndSubtract(result)
		End Function

		Public Function Multiply(ByVal n1 As Double, ByVal n2 As Double) As Double Implements Microsoft.ServiceModel.Samples.ICalculator.Multiply
			Return MyBase.Channel.Multiply(n1, n2)
		End Function

		Public Function BeginMultiply(ByVal n1 As Double, ByVal n2 As Double, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements Microsoft.ServiceModel.Samples.ICalculator.BeginMultiply
			Return MyBase.Channel.BeginMultiply(n1, n2, callback, asyncState)
		End Function

		Public Function EndMultiply(ByVal result As System.IAsyncResult) As Double Implements Microsoft.ServiceModel.Samples.ICalculator.EndMultiply
			Return MyBase.Channel.EndMultiply(result)
		End Function

		Public Function Divide(ByVal n1 As Double, ByVal n2 As Double) As Double Implements Microsoft.ServiceModel.Samples.ICalculator.Divide
			Return MyBase.Channel.Divide(n1, n2)
		End Function

		Public Function BeginDivide(ByVal n1 As Double, ByVal n2 As Double, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult Implements Microsoft.ServiceModel.Samples.ICalculator.BeginDivide
			Return MyBase.Channel.BeginDivide(n1, n2, callback, asyncState)
		End Function

		Public Function EndDivide(ByVal result As System.IAsyncResult) As Double Implements Microsoft.ServiceModel.Samples.ICalculator.EndDivide
			Return MyBase.Channel.EndDivide(result)
		End Function
	End Class
End Namespace
