all: IUnknownSerialization.exe
 
IUnknownSerialization.exe: IUnknownSerialization.vb
 vbc /t:exe IUnknownSerialization.vb /r:System.ServiceModel.dll,System.Runtime.Serialization.dll /libpath:c:\whidbey\assemblies