all: c_FindClaimsPerf.exe
 
c_FindClaimsPerf.exe: c_FindClaimsPerf.cs 
 csc /t:exe c_FindClaimsPerf.cs /r:System.ServiceModel.dll,System.Runtime.Serialization.dll,System.IdentityModel.dll /lib:c:\whidbey\assemblies
