all: service.dll
 
service.dll: c_HowTo_EnableStreaming_code.cs 
 csc /t:library c_HowTo_EnableStreaming_code.cs /r:System.ServiceModel.dll,System.Runtime.Serialization.dll,System.IdentityModel.dll /lib:c:\whidbey\assemblies