all: instance.exe 
 
instance.exe: instance.cs 
 csc /t:exe /out:instance.exe instance.cs /r:System.dll,System.ServiceModel.dll,System.Data.dll,System.IdentityModel.dll,System.Xml.dll,System.Security.dll,System.Configuration.dll /lib:c:\whidbey\assemblies
 
