IListSource.exe:  BusinessObjectBase.cs Employee.cs EmployeeListSource.cs Form1.cs 
   csc /t:exe /out:IListSource.exe BusinessObjectBase.cs Employee.cs EmployeeListSource.cs Form1.cs  

clean:
   del *.dll *.bin *.exe