all: XsdDataContractImporterExample.exe 
XsdDataContractImporterExample.exe: XsdDataContractImporterExample.cs
 csc /t:exe XsdDataContractImporterExample.cs /r:System.ServiceModel.dll,System.Runtime.Serialization.dll /lib:C:\Whidbey\assemblies