# In the line of script below that starts with XCOPY, replace
# the myfile placeholder with the filename + extension that you 
# want Parsnip to dynamically compile during testing.

all:
	IF NOT EXIST App_Code md App_Code
	XCOPY persistencemodeattributesamples.cs App_Code /c /o /r /y
