name: "C# 15 - New feature - Errors and warnings"
description: Create the issue for adding reference docs for new compiler warnings and errors added in a new feature in C# 15 
title: "[C# 15-Errors and warnings]: New Feature - "
labels:
  - ":checkered_flag: Release: .NET 11"
  - okr-curation
  - dotnet-csharp/svc
  - whats-new/subsvc
assignees:
 - billwagner
body:
  - type: dropdown
    id: version
    attributes:
      label: .NET 11 Preview
      description: Which .NET 11 preview version contains this feature?
      options:
        - ".NET 11 preview 1"
        - ".NET 11 preview 2"
        - ".NET 11 preview 3"
        - ".NET 11 preview 4"
        - ".NET 11 preview 5"
        - ".NET 11 preview 6"
        - ".NET 11 preview 7"
        - "other - specify below"
  - type: input
    id: Speclet
    attributes:
      label: Link to speclet
      description: Insert the markdown format for a link to the speclet
      value: "- [Speclet](https://github.com/dotnet/csharplang/blob/main/proposals/feature.md)"
    validations:
      required: true
  - type: input
    id: pullrequest
    attributes:
      label: Link to Pull request
      description: Insert the markdown format for a link to the PR
      value: "- [PR](https://github.com/dotnet/roslyn/pull/nnnnn)"
    validations:
      required: true
  - type: textarea
    id: errors-warnings
    attributes:
      label: Errors and warnings added for this feature
      description: Add the list of IDs and message from the relevant PR
      placeholder: |
        - CSnnnn: Message
  - type: textarea
    id: theme
    attributes:
      label: What language theme applies, for consolidation of articles
      description: Consider what syntax areas are affected for consolidating existing errors and warnings
      placeholder: |
        Consider themes in syntax affected by the new set of errors are warnings
