name: ".NET breaking change"
description: Report a change in .NET that breaks something that worked in a previous version. Intended mostly for product-team use.
title: "[Breaking change]: "
labels:
  - breaking-change
  - Pri1
  - doc-idea
assignees:
 - gewarren
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief description of the breaking change.
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of .NET introduced the breaking change?
      options:
        - .NET 7
        - .NET 8 Preview 1
        - .NET 8 Preview 2
        - .NET 8 Preview 3
        - .NET 8 Preview 4
        - .NET 8 Preview 5
        - .NET 8 Preview 6
        - .NET 8 Preview 7
        - .NET 8 RC 1
        - .NET 8 RC 2
        - .NET 8 (other)
        - Other (please put exact version in description textbox)
    validations:
      required: true
  - type: textarea
    id: old-behavior
    attributes:
      label: Previous behavior
      description: Describe the previous behavior.
    validations:
      required: true
  - type: textarea
    id: new-behavior
    attributes:
      label: New behavior
      description: Describe the new behavior. Include code snippets if applicable.
    validations:
      required: true
  - type: checkboxes
    id: change-type
    attributes:
      label: Type of breaking change
      description: This information will be used to label the issue appropriately. [(How do I decide?)](https://learn.microsoft.com/dotnet/core/compatibility/categories)
      options:
        - label: "**Binary incompatible**: Existing binaries may encounter a breaking change in behavior, such as failure to load or execute, and if so, require recompilation."
        - label:  "**Source incompatible**: When recompiled using the new SDK or component or to target the new runtime, existing source code may require source changes to compile successfully."
        - label:  "**Behavioral change**: Existing binaries may behave differently at run time."
  - type: textarea
    id: reason
    attributes:
      label: Reason for change
      description: Describe why the breaking change was introduced.
    validations:
      required: true
  - type: textarea
    id: recommended-action
    attributes:
      label: Recommended action
      description: Describe the recommended action an affected user should take, such as workarounds or examples of code changes.
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Feature area
      description: What feature area(s) does the change affect?
      multiple: true
      options:
        - ASP.NET Core
        - C#
        - Code analysis
        - Containers
        - Core .NET libraries
        - Cryptography
        - Debugger
        - Deployment
        - Extensions
        - Globalization
        - Interop
        - JIT
        - LINQ
        - .NET MAUI
        - Networking
        - SDK
        - Security
        - Serialization
        - Visual Basic
        - WCF Client
        - Windows Forms
        - Windows Presentation Foundation (WPF)
        - XML, XSLT
        - Other (please put exact area in description textbox)
    validations:
      required: true
  - type: textarea
    id: affected-apis
    attributes:
      label: Affected APIs
      description: List all the APIs affected by this change. For methods, clarify if it's all overloads or specific overloads.
  - type: markdown
    attributes:
      value: |
        Finally, please email a link to this breaking change issue to [.NET Breaking Change Notifications](mailto:dotnetbcn@microsoft.com).
