name: Feedback from live site
description: |
  This template is hooked into the feedback control on the bottom of every page on the live site. It automatically fills in several fields for you. You should not use this template for other purposes.
body:
  - type: textarea
    id: feedback
    validations:
      required: true
    attributes:
      label: Short description
      description: >-
        Write a clear and concise description of the issue for this article.
  - type: textarea
    id: details
    validations:
      required: true
    attributes:
      label: Details
      description: >-
        Provide details that will add context and help the team address your feedback.
  - type: input
    id: pageUrl
    validations:
      required: true
    attributes:
      label: Page URL
  - type: input
    id: contentSourceUrl
    validations:
      required: true
    attributes:
      label: Content source URL
  - type: input
    id: documentVersionIndependentId
    validations:
      required: true
    attributes:
      label: Document Version Independent Id
  - type: input
    id: author
    validations:
      required: true
    attributes:
      label: Author
