name: Feedback from live site
title: "[Documentation feedback] - "
description: |
  This template is hooked into the feedback control on the bottom of every page on the live site. It automatically fills in several fields for you. You should not use this template for other purposes.
labels:
  - ":watch: Not Triaged"
body:
  - type: textarea
    id: details
    validations:
      required: true
    attributes:
      label: Details
      description: >-
        Write a clear and concise description of your feedback for the documentation. 
        Provide details that will add context and help the team address your feedback.
  - type: input
    id: pageUrl
    validations:
      required: true
    attributes:
      label: Page URL
  - type: input
    id: contentSourceUrl
    validations:
      required: true
    attributes:
      label: Content source URL
  - type: input
    id: documentId
    validations:
      required: true
    attributes:
      label: Document Id
