name: Learn feedback control.
description: |
  ⛔ This template is hooked into the feedback control on the bottom of every page on the live site. It automatically fills in several fields for you. Don't use for other purposes. ⛔
body:
  - type: markdown
    attributes:
      value: >-
        Before opening a new issues, check existing issues
        [on this article](https://github.com/dotnet/docs/issues?q=is%3Aissue+db96afbb-50af-5dee-b7b3-97600161e737)
        to see if something similar has already been reported. You can add additional
        information on an existing issue.
  - type: markdown
    attributes:
      value: "## Issue information"
  - type: markdown
    attributes:
      value: Select the issue type, and describe the issue in the text box below. Add as much detail as needed to help us resolve the issue.
  - type: dropdown
    id: issue-type
    attributes:
      label: Type of issue
      options:
        - Typo
        - Code doesn't work
        - Missing information
        - Outdated article
        - Thank you
        - Other (describe below)
    validations:
      required: true
  - type: textarea
    id: feedback
    validations:
      required: true
    attributes:
      label: Description
  - type: markdown
    attributes:
      value: "## 🚧 Article information 🚧"
  - type: markdown
    attributes:
      value: "*Don't modify the following fields*. They are automatically filled in for you. Doing so will disconnect your issue from the affected article. *Don't edit them*."
  - type: input
    id: pageUrl
    validations:
      required: true
    attributes:
      label: Page URL
  - type: input
    id: contentSourceUrl
    validations:
      required: true
    attributes:
      label: Content source URL
  - type: input
    id: documentVersionIndependentId
    validations:
      required: true
    attributes:
      label: Document Version Independent Id
  - type: input
    id: author
    validations:
      required: true
    attributes:
      label: Article author
  - type: textarea
    id: metadata
    validations:
      required: false
    attributes:
      label: Metadata
      description: >-
        Documentation metadata will be applied here for the PRMerger tool
