all: source.exe
 
source.exe: source.vb
 vbc /t:exe source.vb /r:System.Web.ApplicationServices.dll,System.ServiceModel.dll,System.dll,System.Configuration.dll,System.Runtime.Serialization.dll,System.IdentityModel.dll 
