DataflowBatchDatabase.exe : DataflowBatchDatabase.cs
                            csc.exe /lib:"C:\Program Files\Microsoft SQL Server Compact Edition\v3.5\Desktop" /r:System.Threading.Tasks.Dataflow.dll;System.Data.SqlServerCe.dll DataflowBatchDatabase.cs
