all: c_CustomAuthPol.exe
 
c_CustomAuthPol.exe: c_CustomAuthPol.cs 
 csc /t:exe c_CustomAuthPol.cs /r:System.ServiceModel.dll,System.Runtime.Serialization.dll,System.IdentityModel.dll /lib:c:\whidbey\assemblies
