all: c_CustomBinding.exe
 
c_CustomBinding.exe: c_CustomBinding.cs
 csc /t:library c_CustomBinding.cs /r:System.ServiceModel.dll,System.Runtime.Serialization.dll,System.IdentityModel.dll /lib:c:\whidbey\assemblies 