client.exe: client.cs generatedProxy.cs
 csc /t:exe *.cs /r:System.ServiceModel.dll,System.Data.dll,System.IdentityModel.dll,System.Security.dll,System.ServiceModel.dll,System.Xml.dll /lib:c:\whidbey\assemblies
