'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30306.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


'Original file name:
'Generation date: 3/20/2010 11:34:11 AM
Namespace Northwind
    '''<summary>
    '''There are no comments for NorthwindEntities in the schema.
    '''</summary>
    Partial Public Class NorthwindEntities
        Inherits Global.System.Data.Services.Client.DataServiceContext
        '''<summary>
        '''Initialize a new NorthwindEntities object.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub New(ByVal serviceRoot As Global.System.Uri)
            MyBase.New(serviceRoot)
            Me.ResolveName = AddressOf Me.ResolveNameFromType
            Me.ResolveType = AddressOf Me.ResolveTypeFromName
            Me.OnContextCreated
        End Sub
        Partial Private Sub OnContextCreated()
        End Sub
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private Shared ROOTNAMESPACE As String = GetType(Northwind.NorthwindEntities).Namespace.Remove(GetType(Northwind.NorthwindEntities).Namespace.LastIndexOf("Northwind"))
        '''<summary>
        '''Since the namespace configured for this service reference
        '''in Visual Studio is different from the one indicated in the
        '''server schema, use type-mappers to map between the two.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Function ResolveTypeFromName(ByVal typeName As String) As Global.System.Type
            If typeName.StartsWith("NorthwindModel", Global.System.StringComparison.OrdinalIgnoreCase) Then
                Return Me.GetType.Assembly.GetType(String.Concat(String.Concat(ROOTNAMESPACE, "Northwind"), typeName.Substring(14)), false)
            End If
            Return Nothing
        End Function
        '''<summary>
        '''Since the namespace configured for this service reference
        '''in Visual Studio is different from the one indicated in the
        '''server schema, use type-mappers to map between the two.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Function ResolveNameFromType(ByVal clientType As Global.System.Type) As String
            If clientType.Namespace.Equals(String.Concat(ROOTNAMESPACE, "Northwind"), Global.System.StringComparison.OrdinalIgnoreCase) Then
                Return String.Concat("NorthwindModel.", clientType.Name)
            End If
            Return Nothing
        End Function
        '''<summary>
        '''There are no comments for Customers in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property Customers() As Global.System.Data.Services.Client.DataServiceQuery(Of Customer)
            Get
                If (Me._Customers Is Nothing) Then
                    Me._Customers = MyBase.CreateQuery(Of Customer)("Customers")
                End If
                Return Me._Customers
            End Get
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Customers As Global.System.Data.Services.Client.DataServiceQuery(Of Customer)
        '''<summary>
        '''There are no comments for Order_Details in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property Order_Details() As Global.System.Data.Services.Client.DataServiceQuery(Of Order_Detail)
            Get
                If (Me._Order_Details Is Nothing) Then
                    Me._Order_Details = MyBase.CreateQuery(Of Order_Detail)("Order_Details")
                End If
                Return Me._Order_Details
            End Get
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Order_Details As Global.System.Data.Services.Client.DataServiceQuery(Of Order_Detail)
        '''<summary>
        '''There are no comments for Orders in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public ReadOnly Property Orders() As Global.System.Data.Services.Client.DataServiceQuery(Of Order)
            Get
                If (Me._Orders Is Nothing) Then
                    Me._Orders = MyBase.CreateQuery(Of Order)("Orders")
                End If
                Return Me._Orders
            End Get
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Orders As Global.System.Data.Services.Client.DataServiceQuery(Of Order)
        '''<summary>
        '''There are no comments for Customers in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToCustomers(ByVal customer As Customer)
            MyBase.AddObject("Customers", customer)
        End Sub
        '''<summary>
        '''There are no comments for Order_Details in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToOrder_Details(ByVal order_Detail As Order_Detail)
            MyBase.AddObject("Order_Details", order_Detail)
        End Sub
        '''<summary>
        '''There are no comments for Orders in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Sub AddToOrders(ByVal order As Order)
            MyBase.AddObject("Orders", order)
        End Sub
    End Class
    '''<summary>
    '''There are no comments for NorthwindModel.Customer in the schema.
    '''</summary>
    '''<KeyProperties>
    '''CustomerID
    '''</KeyProperties>
    <Global.System.Data.Services.Common.EntitySetAttribute("Customers"),  _
     Global.System.Data.Services.Common.DataServiceKeyAttribute("CustomerID")>  _
    Partial Public Class Customer
        Implements Global.System.ComponentModel.INotifyPropertyChanged
        '''<summary>
        '''Create a new Customer object.
        '''</summary>
        '''<param name="customerID">Initial value of CustomerID.</param>
        '''<param name="companyName">Initial value of CompanyName.</param>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateCustomer(ByVal customerID As String, ByVal companyName As String) As Customer
            Dim customer As Customer = New Customer()
            customer.CustomerID = customerID
            customer.CompanyName = companyName
            Return customer
        End Function
        '''<summary>
        '''There are no comments for Property CustomerID in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property CustomerID() As String
            Get
                Return Me._CustomerID
            End Get
            Set
                Me.OnCustomerIDChanging(value)
                Me._CustomerID = value
                Me.OnCustomerIDChanged
                Me.OnPropertyChanged("CustomerID")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _CustomerID As String
        Partial Private Sub OnCustomerIDChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnCustomerIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property CompanyName in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property CompanyName() As String
            Get
                Return Me._CompanyName
            End Get
            Set
                Me.OnCompanyNameChanging(value)
                Me._CompanyName = value
                Me.OnCompanyNameChanged
                Me.OnPropertyChanged("CompanyName")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _CompanyName As String
        Partial Private Sub OnCompanyNameChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnCompanyNameChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ContactName in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ContactName() As String
            Get
                Return Me._ContactName
            End Get
            Set
                Me.OnContactNameChanging(value)
                Me._ContactName = value
                Me.OnContactNameChanged
                Me.OnPropertyChanged("ContactName")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ContactName As String
        Partial Private Sub OnContactNameChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnContactNameChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ContactTitle in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ContactTitle() As String
            Get
                Return Me._ContactTitle
            End Get
            Set
                Me.OnContactTitleChanging(value)
                Me._ContactTitle = value
                Me.OnContactTitleChanged
                Me.OnPropertyChanged("ContactTitle")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ContactTitle As String
        Partial Private Sub OnContactTitleChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnContactTitleChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Address in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Address() As String
            Get
                Return Me._Address
            End Get
            Set
                Me.OnAddressChanging(value)
                Me._Address = value
                Me.OnAddressChanged
                Me.OnPropertyChanged("Address")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Address As String
        Partial Private Sub OnAddressChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnAddressChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property City in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property City() As String
            Get
                Return Me._City
            End Get
            Set
                Me.OnCityChanging(value)
                Me._City = value
                Me.OnCityChanged
                Me.OnPropertyChanged("City")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _City As String
        Partial Private Sub OnCityChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnCityChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Region in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Region() As String
            Get
                Return Me._Region
            End Get
            Set
                Me.OnRegionChanging(value)
                Me._Region = value
                Me.OnRegionChanged
                Me.OnPropertyChanged("Region")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Region As String
        Partial Private Sub OnRegionChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnRegionChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property PostalCode in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property PostalCode() As String
            Get
                Return Me._PostalCode
            End Get
            Set
                Me.OnPostalCodeChanging(value)
                Me._PostalCode = value
                Me.OnPostalCodeChanged
                Me.OnPropertyChanged("PostalCode")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _PostalCode As String
        Partial Private Sub OnPostalCodeChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnPostalCodeChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Country in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Country() As String
            Get
                Return Me._Country
            End Get
            Set
                Me.OnCountryChanging(value)
                Me._Country = value
                Me.OnCountryChanged
                Me.OnPropertyChanged("Country")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Country As String
        Partial Private Sub OnCountryChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnCountryChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Phone in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Phone() As String
            Get
                Return Me._Phone
            End Get
            Set
                Me.OnPhoneChanging(value)
                Me._Phone = value
                Me.OnPhoneChanged
                Me.OnPropertyChanged("Phone")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Phone As String
        Partial Private Sub OnPhoneChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnPhoneChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Fax in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Fax() As String
            Get
                Return Me._Fax
            End Get
            Set
                Me.OnFaxChanging(value)
                Me._Fax = value
                Me.OnFaxChanged
                Me.OnPropertyChanged("Fax")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Fax As String
        Partial Private Sub OnFaxChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnFaxChanged()
        End Sub
        '''<summary>
        '''There are no comments for Orders in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Orders() As Global.System.Data.Services.Client.DataServiceCollection(Of Order)
            Get
                Return Me._Orders
            End Get
            Set
                Me._Orders = value
                Me.OnPropertyChanged("Orders")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Orders As Global.System.Data.Services.Client.DataServiceCollection(Of Order) = New Global.System.Data.Services.Client.DataServiceCollection(Of Order)(Nothing, System.Data.Services.Client.TrackingMode.None)
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
            End If
        End Sub
    End Class
    '''<summary>
    '''There are no comments for NorthwindModel.Order_Detail in the schema.
    '''</summary>
    '''<KeyProperties>
    '''OrderID
    '''ProductID
    '''</KeyProperties>
    <Global.System.Data.Services.Common.EntitySetAttribute("Order_Details"),  _
     Global.System.Data.Services.Common.DataServiceKeyAttribute("OrderID", "ProductID")>  _
    Partial Public Class Order_Detail
        Implements Global.System.ComponentModel.INotifyPropertyChanged
        '''<summary>
        '''Create a new Order_Detail object.
        '''</summary>
        '''<param name="orderID">Initial value of OrderID.</param>
        '''<param name="productID">Initial value of ProductID.</param>
        '''<param name="unitPrice">Initial value of UnitPrice.</param>
        '''<param name="quantity">Initial value of Quantity.</param>
        '''<param name="discount">Initial value of Discount.</param>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateOrder_Detail(ByVal orderID As Integer, ByVal productID As Integer, ByVal unitPrice As Decimal, ByVal quantity As Short, ByVal discount As Single) As Order_Detail
            Dim order_Detail As Order_Detail = New Order_Detail()
            order_Detail.OrderID = orderID
            order_Detail.ProductID = productID
            order_Detail.UnitPrice = unitPrice
            order_Detail.Quantity = quantity
            order_Detail.Discount = discount
            Return order_Detail
        End Function
        '''<summary>
        '''There are no comments for Property OrderID in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property OrderID() As Integer
            Get
                Return Me._OrderID
            End Get
            Set
                Me.OnOrderIDChanging(value)
                Me._OrderID = value
                Me.OnOrderIDChanged
                Me.OnPropertyChanged("OrderID")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _OrderID As Integer
        Partial Private Sub OnOrderIDChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnOrderIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ProductID in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ProductID() As Integer
            Get
                Return Me._ProductID
            End Get
            Set
                Me.OnProductIDChanging(value)
                Me._ProductID = value
                Me.OnProductIDChanged
                Me.OnPropertyChanged("ProductID")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ProductID As Integer
        Partial Private Sub OnProductIDChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnProductIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property UnitPrice in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property UnitPrice() As Decimal
            Get
                Return Me._UnitPrice
            End Get
            Set
                Me.OnUnitPriceChanging(value)
                Me._UnitPrice = value
                Me.OnUnitPriceChanged
                Me.OnPropertyChanged("UnitPrice")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _UnitPrice As Decimal
        Partial Private Sub OnUnitPriceChanging(ByVal value As Decimal)
        End Sub
        Partial Private Sub OnUnitPriceChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Quantity in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Quantity() As Short
            Get
                Return Me._Quantity
            End Get
            Set
                Me.OnQuantityChanging(value)
                Me._Quantity = value
                Me.OnQuantityChanged
                Me.OnPropertyChanged("Quantity")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Quantity As Short
        Partial Private Sub OnQuantityChanging(ByVal value As Short)
        End Sub
        Partial Private Sub OnQuantityChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Discount in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Discount() As Single
            Get
                Return Me._Discount
            End Get
            Set
                Me.OnDiscountChanging(value)
                Me._Discount = value
                Me.OnDiscountChanged
                Me.OnPropertyChanged("Discount")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Discount As Single
        Partial Private Sub OnDiscountChanging(ByVal value As Single)
        End Sub
        Partial Private Sub OnDiscountChanged()
        End Sub
        '''<summary>
        '''There are no comments for Order in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Order() As Order
            Get
                Return Me._Order
            End Get
            Set
                Me._Order = value
                Me.OnPropertyChanged("Order")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Order As Order
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
            End If
        End Sub
    End Class
    '''<summary>
    '''There are no comments for NorthwindModel.Order in the schema.
    '''</summary>
    '''<KeyProperties>
    '''OrderID
    '''</KeyProperties>
    <Global.System.Data.Services.Common.EntitySetAttribute("Orders"),  _
     Global.System.Data.Services.Common.DataServiceKeyAttribute("OrderID")>  _
    Partial Public Class Order
        Implements Global.System.ComponentModel.INotifyPropertyChanged
        '''<summary>
        '''Create a new Order object.
        '''</summary>
        '''<param name="orderID">Initial value of OrderID.</param>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Shared Function CreateOrder(ByVal orderID As Integer) As Order
            Dim order As Order = New Order()
            order.OrderID = orderID
            Return order
        End Function
        '''<summary>
        '''There are no comments for Property OrderID in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property OrderID() As Integer
            Get
                Return Me._OrderID
            End Get
            Set
                Me.OnOrderIDChanging(value)
                Me._OrderID = value
                Me.OnOrderIDChanged
                Me.OnPropertyChanged("OrderID")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _OrderID As Integer
        Partial Private Sub OnOrderIDChanging(ByVal value As Integer)
        End Sub
        Partial Private Sub OnOrderIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property CustomerID in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property CustomerID() As String
            Get
                Return Me._CustomerID
            End Get
            Set
                Me.OnCustomerIDChanging(value)
                Me._CustomerID = value
                Me.OnCustomerIDChanged
                Me.OnPropertyChanged("CustomerID")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _CustomerID As String
        Partial Private Sub OnCustomerIDChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnCustomerIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property EmployeeID in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property EmployeeID() As Global.System.Nullable(Of Integer)
            Get
                Return Me._EmployeeID
            End Get
            Set
                Me.OnEmployeeIDChanging(value)
                Me._EmployeeID = value
                Me.OnEmployeeIDChanged
                Me.OnPropertyChanged("EmployeeID")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _EmployeeID As Global.System.Nullable(Of Integer)
        Partial Private Sub OnEmployeeIDChanging(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
        Partial Private Sub OnEmployeeIDChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property OrderDate in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property OrderDate() As Global.System.Nullable(Of Date)
            Get
                Return Me._OrderDate
            End Get
            Set
                Me.OnOrderDateChanging(value)
                Me._OrderDate = value
                Me.OnOrderDateChanged
                Me.OnPropertyChanged("OrderDate")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _OrderDate As Global.System.Nullable(Of Date)
        Partial Private Sub OnOrderDateChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
        Partial Private Sub OnOrderDateChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property RequiredDate in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property RequiredDate() As Global.System.Nullable(Of Date)
            Get
                Return Me._RequiredDate
            End Get
            Set
                Me.OnRequiredDateChanging(value)
                Me._RequiredDate = value
                Me.OnRequiredDateChanged
                Me.OnPropertyChanged("RequiredDate")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _RequiredDate As Global.System.Nullable(Of Date)
        Partial Private Sub OnRequiredDateChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
        Partial Private Sub OnRequiredDateChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ShippedDate in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ShippedDate() As Global.System.Nullable(Of Date)
            Get
                Return Me._ShippedDate
            End Get
            Set
                Me.OnShippedDateChanging(value)
                Me._ShippedDate = value
                Me.OnShippedDateChanged
                Me.OnPropertyChanged("ShippedDate")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ShippedDate As Global.System.Nullable(Of Date)
        Partial Private Sub OnShippedDateChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
        Partial Private Sub OnShippedDateChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ShipVia in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ShipVia() As Global.System.Nullable(Of Integer)
            Get
                Return Me._ShipVia
            End Get
            Set
                Me.OnShipViaChanging(value)
                Me._ShipVia = value
                Me.OnShipViaChanged
                Me.OnPropertyChanged("ShipVia")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ShipVia As Global.System.Nullable(Of Integer)
        Partial Private Sub OnShipViaChanging(ByVal value As Global.System.Nullable(Of Integer))
        End Sub
        Partial Private Sub OnShipViaChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property Freight in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Freight() As Global.System.Nullable(Of Decimal)
            Get
                Return Me._Freight
            End Get
            Set
                Me.OnFreightChanging(value)
                Me._Freight = value
                Me.OnFreightChanged
                Me.OnPropertyChanged("Freight")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Freight As Global.System.Nullable(Of Decimal)
        Partial Private Sub OnFreightChanging(ByVal value As Global.System.Nullable(Of Decimal))
        End Sub
        Partial Private Sub OnFreightChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ShipName in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ShipName() As String
            Get
                Return Me._ShipName
            End Get
            Set
                Me.OnShipNameChanging(value)
                Me._ShipName = value
                Me.OnShipNameChanged
                Me.OnPropertyChanged("ShipName")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ShipName As String
        Partial Private Sub OnShipNameChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnShipNameChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ShipAddress in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ShipAddress() As String
            Get
                Return Me._ShipAddress
            End Get
            Set
                Me.OnShipAddressChanging(value)
                Me._ShipAddress = value
                Me.OnShipAddressChanged
                Me.OnPropertyChanged("ShipAddress")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ShipAddress As String
        Partial Private Sub OnShipAddressChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnShipAddressChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ShipCity in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ShipCity() As String
            Get
                Return Me._ShipCity
            End Get
            Set
                Me.OnShipCityChanging(value)
                Me._ShipCity = value
                Me.OnShipCityChanged
                Me.OnPropertyChanged("ShipCity")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ShipCity As String
        Partial Private Sub OnShipCityChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnShipCityChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ShipRegion in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ShipRegion() As String
            Get
                Return Me._ShipRegion
            End Get
            Set
                Me.OnShipRegionChanging(value)
                Me._ShipRegion = value
                Me.OnShipRegionChanged
                Me.OnPropertyChanged("ShipRegion")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ShipRegion As String
        Partial Private Sub OnShipRegionChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnShipRegionChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ShipPostalCode in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ShipPostalCode() As String
            Get
                Return Me._ShipPostalCode
            End Get
            Set
                Me.OnShipPostalCodeChanging(value)
                Me._ShipPostalCode = value
                Me.OnShipPostalCodeChanged
                Me.OnPropertyChanged("ShipPostalCode")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ShipPostalCode As String
        Partial Private Sub OnShipPostalCodeChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnShipPostalCodeChanged()
        End Sub
        '''<summary>
        '''There are no comments for Property ShipCountry in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property ShipCountry() As String
            Get
                Return Me._ShipCountry
            End Get
            Set
                Me.OnShipCountryChanging(value)
                Me._ShipCountry = value
                Me.OnShipCountryChanged
                Me.OnPropertyChanged("ShipCountry")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _ShipCountry As String
        Partial Private Sub OnShipCountryChanging(ByVal value As String)
        End Sub
        Partial Private Sub OnShipCountryChanged()
        End Sub
        '''<summary>
        '''There are no comments for Customer in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Customer() As Customer
            Get
                Return Me._Customer
            End Get
            Set
                Me._Customer = value
                Me.OnPropertyChanged("Customer")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Customer As Customer
        '''<summary>
        '''There are no comments for Order_Details in the schema.
        '''</summary>
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Property Order_Details() As Global.System.Data.Services.Client.DataServiceCollection(Of Order_Detail)
            Get
                Return Me._Order_Details
            End Get
            Set
                Me._Order_Details = value
                Me.OnPropertyChanged("Order_Details")
            End Set
        End Property
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Private _Order_Details As Global.System.Data.Services.Client.DataServiceCollection(Of Order_Detail) = New Global.System.Data.Services.Client.DataServiceCollection(Of Order_Detail)(Nothing, System.Data.Services.Client.TrackingMode.None)
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Public Event PropertyChanged As Global.System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")>  _
        Protected Overridable Sub OnPropertyChanged(ByVal [property] As String)
            If (Not (Me.PropertyChangedEvent) Is Nothing) Then
                RaiseEvent PropertyChanged(Me, New Global.System.ComponentModel.PropertyChangedEventArgs([property]))
            End If
        End Sub
    End Class
End Namespace
