<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>TreeWalkerTarget</RootNamespace>
    <AssemblyName>TreeWalkerTarget</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="TreeWalkerTarget.cs" />
    <Compile Include="TreeWalkerTarget.Designer.cs" />
  </ItemGroup>

</Project>
