<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RootNamespace>NavigateWithTreeWalker</RootNamespace>
    <AssemblyName>TreeWalkerClient</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="ClientClass.cs" />
    <Compile Include="ClientForm.cs" />
    <Compile Include="ClientForm.Designer.cs" />
    <Compile Include="ClientProgram.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="app.config" />
  </ItemGroup>
</Project>
