all : net_async.exe nmake_async.exe sort_async.exe

net_async.exe : net_async.cs
	csc net_async.cs

nmake_async.exe : nmake_async.cs
	csc nmake_async.cs

sort_async.exe :  sort_async.cs
	csc  sort_async.cs