MaskInputRejectedSample.dll: form1.cs Form1.Designer.cs Program.cs
   csc /t:library /out:MaskInputRejectedSample.dll form1.cs Form1.Designer.cs Program.cs

clean: MaskInputRejectedSample.dll
   del *.dll *.bin
