' <snippet1>
' Create a code-behind user control that is cached
' for 20 seconds and uses the VaryByParams property
' to vary the cached control according to the value of the 
' specified control.

' <snippet2>
' Set the PartialCachingAttribute.Duration property to
' 20 seconds and the PartialCachingAttribute.VaryByParams
' property to ctlSelect.country, the full name of the form 
' POST parameter generated by the country DropDownList control.
<PartialCaching(20, "ctlSelect.country", Nothing, Nothing)> _
Public Class ctlSelect
    Inherits UserControl
    ' </snippet2>

    Protected Sub Page_Load(ByVal sender As [Object], ByVal e As EventArgs)
        If Not IsPostBack Then
            TimeMsg.Text = DateTime.Now.ToString("T")
        End If
    End Sub 'Page_Load


    Protected Sub SubmitBtn_Click(ByVal Sender As [Object], ByVal e As EventArgs)
        Label1.Text = "You chose: " & state.SelectedItem.Text & " and " & country.SelectedItem.Text & "."

        TimeMsg.Text = DateTime.Now.ToString("T")
    End Sub 'SubmitBtn_Click
End Class 'ctlSelect
' </snippet1>