all: DataGridViewBandDemo.exe DataGridViewColumnDemo.exe DataGridViewRowDemo.exe

DataGridViewBandDemo.exe: DataGridViewBandDemo.cpp
	cl /clr:pure DataGridViewBandDemo.cpp

DataGridViewColumnDemo.exe: DataGridViewColumnDemo.cpp
	cl /clr:pure DataGridViewColumnDemo.cpp

DataGridViewRowDemo.exe: DataGridViewRowDemo.cpp
	cl /clr:pure DataGridViewRowDemo.cpp