all: source.exe
 
source.exe: source.cs 
 csc /t:exe *.cs /r:System.dll,System.Configuration.dll,System.ServiceModel.dll,System.Runtime.Serialization.dll,System.IdentityModel.dll,System.Xml.dll, /lib:c:\whidbey\assemblies
