ValidatingTypeSample.dll: form1.cs Form1.Designer.cs Program.cs
   csc /t:library /out:ValidatingTypeSample.dll form1.cs Form1.Designer.cs Program.cs

clean: ValidatingTypeSample.dll
   del *.dll *.bin
