MarqueeControlLibrary.dll:  IMarqueeWidget.vb LightShapeSelectionControl.vb MarqueeBorder.vb MarqueeControl.vb MarqueeText.vb MarqueeControlRootDesigner.vb MarqueeBorderDesigner.vb
   vbc /t:library /out:MarqueeControlLibrary.dll IMarqueeWidget.vb LightShapeSelectionControl.vb MarqueeBorder.vb MarqueeControl.vb MarqueeText.vb MarqueeControlRootDesigner.vb MarqueeBorderDesigner.vb

clean:
   del *.dll *.bin