all: 
	IF NOT EXIST App_Code md App_Code 
	XCOPY AppStart.cs App_Code /c /o /r /y 
	XCOPY SamplePathProvider.cs App_Code /c /o /r /y 
	XCOPY SampleVirtualDirectory.cs App_Code /c /o /r /y 
	XCOPY SampleVirtualFile.cs App_Code /c /o /r /y 
