all: XsdDataContractImporterExample.exe 
XsdDataContractImporterExample.exe: XsdDataContractImporterExample.vb
 vbc /t:exe *.vb /r:System.ServiceModel.dll,System.Runtime.Serialization.dll /libpath:C:\Whidbey\Assemblies