all: AuditingSecurityEvents.exe
 
AuditingSecurityEvents.exe: AuditingSecurityEvents.cs 
 csc /t:exe AuditingSecurityEvents.cs /r:System.ServiceModel.dll,System.Runtime.Serialization.dll /lib:c:\whidbey\assemblies
