WSHttpBinding.exe: WSHttpBinding.cs
 csc /t:exe WSHttpBinding.cs /r:System.ServiceModel.dll,System.dll,System.Configuration.dll,System.Xml.dll,System.IdentityModel.dll,System.Security.dll /lib:c:\whidbey\assemblies
