all: 
	IF NOT EXIST App_Code md App_Code 
	XCOPY AppStart.vb App_Code /c /o /r /y 
	XCOPY SamplePathProvider.vb App_Code /c /o /r /y 
	XCOPY SampleVirtualDirectory.vb App_Code /c /o /r /y 
	XCOPY SampleVirtualFile.vb App_Code /c /o /r /y 
