        Dim item As SyndicationItem = New SyndicationItem("My Item", "This is some content", New Uri("http:' SomeServer/MyItem"))
        item.Authors.Add(New SyndicationPerson("jesper@contoso.com", "Jesper Aaberg", "http:' contoso/jesper"))
        item.Categories.Add(New SyndicationCategory("Category One"))
        item.Contributors.Add(New SyndicationPerson("lene@contoso.com", "Lene Aaling", "http:' contoso/lene"))
        item.Copyright = New TextSyndicationContent("Copyright 2007")
        item.Links.Add(New SyndicationLink(New Uri("http:' OtherServer/Item"), "alternate", "Alternate Link", "text/html", 1000))
        item.PublishDate = New DateTime(2007, 2, 23)
        item.Summary = New TextSyndicationContent("this is a summary for my item")