 ' Create a class that does not allow white space generated by a control
 ' to be created as a LiteralControl.   

 <AspNetHostingPermission(SecurityAction.Demand, _
   Level:=AspNetHostingPermissionLevel.Minimal)> _
 Public NotInheritable Class NoWhiteSpaceControlBuilder
   Inherits ControlBuilder
   
   Public Overrides Function AllowWhitespaceLiterals() As Boolean
      Return False
   End Function 'AllowWhitespaceLiterals
 End Class 'NoWhiteSpaceControlBuilder 