Program.exe: service.vb 
 vbc /t:exe service.vb /r:System.dll,System.ServiceModel.dll,System.IdentityModel.dll,System.Xml.dll,System.Configuration.dll,System.Runtime.Serialization.dll /lib:c:\whidbey\assemblies
