HostApplication.exe: HostApplication.cs Services.cs Snippets.cs
 csc /t:exe HostApplication.cs Services.cs Snippets.cs /r:System.dll,System.Configuration.dll,System.ServiceModel.dll,System.Data.dll,System.Xml.dll,System.Runtime.Serialization.dll
