MarqueeControlLibrary.dll:  IMarqueeWidget.cs LightShapeSelectionControl.cs MarqueeBorder.cs MarqueeControl.cs MarqueeText.cs MarqueeControlRootDesigner.cs MarqueeBorderDesigner.cs
   csc /t:library /out:MarqueeControlLibrary.dll IMarqueeWidget.cs LightShapeSelectionControl.cs MarqueeBorder.cs MarqueeControl.cs MarqueeText.cs MarqueeControlRootDesigner.cs MarqueeBorderDesigner.cs

clean:
   del *.dll *.bin