<!-- <Snippet1> -->

<%@ Page language="C#" %>
<%@ import namespace="System.IO" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<script runat="server">

  void CustomersGridView_RowDeleting(Object sender, GridViewDeleteEventArgs e)
  {

    // Record the delete operation in a log file.

    // Create the log text. 
    String logText = "";

    // Append the values of the key fields to the log text.
    foreach (DictionaryEntry keyEntry in e.Keys)
    {
      logText += keyEntry.Key + "=" + keyEntry.Value + ";";
    }

    // Append the values of the non-key fields to the log text.
    foreach (DictionaryEntry valueEntry in e.Values)
    {
      logText += valueEntry.Key + "=" + valueEntry.Value + ";";
    }

    // Display the log content.
    LogTextLabel.Text = logText;
    
    // Append the text to a log file.
    try
    {
      StreamWriter sw;
      sw = File.AppendText(Server.MapPath(null) + "\\deletelog.txt");
      sw.WriteLine(logText);
      sw.Flush();
      sw.Close();
    }
    catch(UnauthorizedAccessException ex)
    {
      // You must provide read/write access to the file using ACLs.
      LogErrorLabel.Text = "You do not have permission to write to the log.";
    }

  }
    
  void CustomersGridView_RowDeleted(Object sender, GridViewDeletedEventArgs e)
  {
    
    if (e.Exception == null)
    {
      // The delete operation succeeded. Clear the message label.
      Message.Text = "";
    }
    else
    {
      // The delete operation failed. Display an error message.
      Message.Text = e.AffectedRows.ToString() + " rows deleted. " + e.Exception.Message;
      e.ExceptionHandled = true;
    }
        
  }

</script>

<html xmlns="http://www.w3.org/1999/xhtml" >
  <head runat="server">
    <title>GridViewDeleteEventArgs Keys and Values Example</title>
</head>
<body>
    <form id="form1" runat="server">
        
      <h3>GridViewDeleteEventArgs Keys and Values Example</h3>
            
      <asp:label id="Message"
        forecolor="Red"          
        runat="server"/>
        
      <br/>
      
      <asp:label id="LogTextLabel"
        forecolor="Red"          
        runat="server"/>
        
      <br/>
        
      <asp:label id="LogErrorLabel"
        forecolor="Red"          
        runat="server"/>
                
      <br/>

      <asp:gridview id="CustomersGridView" 
        allowpaging="true"
        datasourceid="CustomersSqlDataSource" 
        autogeneratecolumns="true"
        autogeneratedeletebutton="true" 
        datakeynames="CustomerID"
        onrowdeleted="CustomersGridView_RowDeleted"
        onrowdeleting="CustomersGridView_RowDeleting"   
        runat="server">
        
      </asp:gridview>
            
      <!-- This example uses Microsoft SQL Server and connects  -->
      <!-- to the Northwind sample database. Use an ASP.NET     -->
      <!-- expression to retrieve the connection string value   -->
      <!-- from the Web.config file.                            -->
      <asp:sqldatasource id="CustomersSqlDataSource"  
        selectcommand="Select [CustomerID], [CompanyName], [Address], [City], [PostalCode], [Country] From [Customers]"
        deletecommand="Delete from Customers where CustomerID = @CustomerID"
        connectionstring="<%$ ConnectionStrings:NorthWindConnectionString%>"
        runat="server">
      </asp:sqldatasource>
            
    </form>
  </body>
</html>

<!-- </Snippet1> -->