all: KnownTypeAttribute_ctor1.exe
 
KnownTypeAttribute_ctor1.exe: KnownTypeAttribute_ctor1.vb 
 vbc /t:exe KnownTypeAttribute_ctor1.vb /r:System.ServiceModel.dll,System.Runtime.Serialization.dll /libpath:c:\whidbey\assemblies