all: IUnknownSerialization.exe
 
IUnknownSerialization.exe: IUnknownSerialization.cs 
 csc /t:exe IUnknownSerialization.cs /r:System.ServiceModel.dll,System.Runtime.Serialization.dll /lib:c:\whidbey\assemblies
