FlashTrackBarTest.exe:  FlashTrackBar.vb FlashTrackBarDarkenByEditor.vb FlashTrackBarValueEditor.vb HostApp.vb
   vbc /t:exe /r:System.Design.dll,System.dll,System.Drawing.dll,System.Windows.Forms.dll /out:FlashTrackBarTest.exe FlashTrackBar.vb FlashTrackBarDarkenByEditor.vb FlashTrackBarValueEditor.vb HostApp.vb

clean:
   del *.exe *.bin