all: c_CustomClaimComparison.exe
 
c_CustomClaimComparison.exe: c_CustomClaimComparison.cs 
 csc /t:exe *.cs /r:System.ServiceModel.dll,System.Runtime.Serialization.dll,System.IdentityModel.dll /lib:c:\whidbey\assemblies
