all: XmlSerializerFormat_Example.exe 
XmlSerializerFormat_Example.exe: XmlSerializerFormat_Example.cs
 csc /t:exe *.cs /r:System.ServiceModel.dll,System.Runtime.Serialization.dll /lib:C:\Whidbey\Assemblies