all: CreationEndpoint.exe

CreationEndpoint.exe: CreationEndpoint.cs CreationEndpointElement.cs Program.cs
   csc /t:exe *.cs /r:System.ServiceModel.dll /r:System.ServiceModel.Activities.dll /r:System.Activities.dll