all: WorkflowApplicationExample.exe

WorkflowApplicationExample.exe: Program.cs
 csc /t:exe Program.cs /r:System.dll /r:System.Activities.dll /r:System.Xaml.dll /r:System.Xml.dll /r:System.Activities.DurableInstancing.dll /r:System.Runtime.DurableInstancing.dll