all: c_FindClaimsPerf.exe
 
c_FindClaimsPerf.exe: c_FindClaimsPerf.vb 
 vbc /t:exe c_FindClaimsPerf.vb /r:System.ServiceModel.dll,System.Runtime.Serialization.dll,System.IdentityModel.dll /lib:c:\whidbey\assemblies
