WSHttpBinding.exe: WSHttpBinding.vb
 vbc /t:exe WSHttpBinding.vb /r:System.ServiceModel.dll,System.dll,System.Configuration.dll,System.Xml.dll,System.IdentityModel.dll,System.Security.dll /lib:c:\whidbey\assemblies
