ComForm.dll:  Form1.vb FormManager.vb COMForm.vb
   vbc /t:library /r:System.dll,System.Drawing.dll,System.Windows.Forms.dll /out:ComForm.dll Form1.vb FormManager.vb COMForm.vb

clean:
   del *.dll *.bin