name: 'OPS status checker'

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  status_checker_job:
    name: Look for build warnings
    runs-on: ubuntu-latest
    permissions:
      statuses: read
      pull-requests: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - uses: dotnet/docs-tools/actions/status-checker@main
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
