name: 'OPS status checker'

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  status_checker_job:
    name: Look for build warnings
    runs-on: ubuntu-latest
    permissions:
      statuses: read
      pull-requests: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - uses: dotnet/docs-tools/actions/status-checker@main
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
