name: 'Preview link generator'

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

jobs:
  preview_link_generator_job:
    name: Generate preview link table
    runs-on: ubuntu-latest
    permissions:
      statuses: read
      pull-requests: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - uses: dotnet/docs-tools/actions/preview-link-generator@main
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          annotate_file_warnings: true
