name: Base branch checker
on: [pull_request]

permissions:
  contents: read

jobs:
  live_protection_job:
    name: Check base branch
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3
        env:
          LIVE_BASE: ${{ github.base_ref == 'live' && github.head_ref != 'main' }}
        with:
          script: |
            if (process.env.LIVE_BASE == 'true') {
              core.setFailed('PR targets live branch')
            }
