name: Base branch checker
on: [pull_request]

permissions:
  contents: read

jobs:
  live_protection_job:
    name: Check base branch
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: audit

      - uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3
        env:
          LIVE_BASE: ${{ github.base_ref == 'live' && github.head_ref != 'main' }}
        with:
          script: |
            if (process.env.LIVE_BASE == 'true') {
              core.setFailed('PR targets live branch')
            }
