name: Markdownlint

on:
  push:
    branches:
      - main
    paths:
      - "**/*.md"
      - ".markdownlint-cli2.jsonc"
      - ".github/workflows/markdownlint.yml"
      - ".github/workflows/markdownlint-problem-matcher.json"
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      statuses: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: DavidAnson/markdownlint-cli2-action@ded1f9488f68a970bc66ea5619e13e9b52e601cd # v23.2.0
        with:
          config: ".markdownlint-cli2.jsonc"
          globs: "**/*.md"
