name: "rebase required"

on:
  push:
  pull_request_target:
    types: [synchronize]

permissions:
  contents: read

jobs:
  label-rebase-needed:
    permissions:
      pull-requests: write  # for eps1lon/actions-label-merge-conflict to label PRs
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c # v2.9.0
        with:
          egress-policy: audit

      - name: Check for merge conflicts
        uses: eps1lon/actions-label-merge-conflict@fd1f295ee7443d13745804bc49fe158e240f6c6e # releases/2.x
        with:
          dirtyLabel: "rebase needed :construction:"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty: This pull request has merge conflicts that must be resolved before it can be merged.
