name: Close stale issues

on:
  schedule: # Run 5 minutes after midnight daily.
  - cron: '5 0 * * *'

permissions:
  contents: read

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
      with:
        egress-policy: audit

    - uses: actions/stale@5f858e3efba33a5ca4407a664cc011ad407f2008
      with:
        start-date: '2022-03-01T00:00:00Z' # ISO 8601 or RFC 2822
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        days-before-stale: 180
        days-before-close: 14
        stale-issue-label: stale
        close-issue-message: >
            This issue has been automatically closed due to lack of activity.
            If you feel this issue is still important, please reopen it and leave a comment.
        exempt-issue-labels: 'breaking-change,Pri0,:watch: Not Triaged,:checkered_flag: Release: .NET 7,:checkered_flag: Release: .NET 8'
        operations-per-run: 50
        debug-only: true
