widgetOptions:
  endpointId: b3da3c4c-9c4e-4411-bc4d-609e2dcc5c67
  displayLabel: Widgets Incorporated, LLC.
  widgetRoute: api/widgets
  ipAddressRange:
    - "46.36.198.123"
    - "46.36.198.124"
    - "46.36.198.125"
  featureFlags:
    isTelemetryEnabled: true
