all: service.dll
 
service.dll: c_HowTo_EnableStreaming_code.vb 
 vbc /t:library c_HowTo_EnableStreaming_code.vb /r:System.ServiceModel.dll,System.Runtime.Serialization.dll,System.IdentityModel.dll /lib:c:\whidbey\assemblies