         MailMessage myMail = new MailMessage();
         myMail.From = "from@microsoft.com";
         myMail.To = "to@microsoft.com";
         myMail.Subject = "UtilMailMessage001";
         myMail.Priority = MailPriority.Low;
         myMail.BodyFormat = MailFormat.Html;
         myMail.Body = "<html><body>UtilMailMessage001 - success</body></html>";
     MailAttachment myAttachment = new MailAttachment("c:\attach\attach1.txt", MailEncoding.Base64);
     myMail.Attachments.Add(myAttachment);
         SmtpMail.SmtpServer = "MyMailServer";
         SmtpMail.Send(myMail);