  // Create a class that does not allow white space generated by a control
  // to be created as a LiteralControl.   
  [AspNetHostingPermission(SecurityAction.Demand, 
     Level=AspNetHostingPermissionLevel.Minimal)]
  public sealed class NoWhiteSpaceControlBuilder : ControlBuilder 
  {  
       public override bool AllowWhitespaceLiterals() 
       {
          return false;
       } 

  }