            channelToken1.EndpointName = "Shipper3Endpoint";
            channelToken1.Name = "Shipper3Endpoint";
            channelToken1.OwnerActivityName = "GetShippingQuotes";
            RequestQuoteFromShipper3.ChannelToken = channelToken1;
            RequestQuoteFromShipper3.Name = "RequestQuoteFromShipper3";
            activityBind2.Name = "SupplierWorkflow";
            activityBind2.Path = "order";
            workflowParameterBinding2.ParameterName = "po";
            workflowParameterBinding2.SetBinding(System.Workflow.ComponentModel.WorkflowParameterBinding.ValueProperty, ((System.Workflow.ComponentModel.ActivityBind)(activityBind2)));
            activityBind3.Name = "SupplierWorkflow";
            activityBind3.Path = "contextShipper3";
            workflowParameterBinding3.ParameterName = "context";
            workflowParameterBinding3.SetBinding(System.Workflow.ComponentModel.WorkflowParameterBinding.ValueProperty, ((System.Workflow.ComponentModel.ActivityBind)(activityBind3)));
            activityBind4.Name = "SupplierWorkflow";
            activityBind4.Path = "ackShipper3";
            workflowParameterBinding4.ParameterName = "(ReturnValue)";
            workflowParameterBinding4.SetBinding(System.Workflow.ComponentModel.WorkflowParameterBinding.ValueProperty, ((System.Workflow.ComponentModel.ActivityBind)(activityBind4)));
            RequestQuoteFromShipper3.ParameterBindings.Add(workflowParameterBinding2);
            RequestQuoteFromShipper3.ParameterBindings.Add(workflowParameterBinding3);
            RequestQuoteFromShipper3.ParameterBindings.Add(workflowParameterBinding4);